name: service

on:
  push:
    branches:
      - main
    paths:
      - service/**
      - .github/workflows/service*.yml
  pull_request:
    branches:
      - main
    paths:
      - service/**
      - .github/workflows/service*.yml

defaults:
  run:
    working-directory: ./service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootJar
